// Generated by Fonts/Source~/build_pixel_fonts.py. Do not edit by hand; change the script and run it.
namespace HoldTheHill.Sandbox.NillyCtrl
{
    /// <summary>
    /// Characters in the Hold the Hill body font (HoldTheHillPixel Regular and Bold) that have no
    /// key on a keyboard: the UI symbols and the key, mouse and gamepad prompts.
    /// Use them in a string, for example <c>$"{PixelGlyphs.KeySpace} START WAVE"</c>.
    /// </summary>
    public static class PixelGlyphs
    {
        public const string ArrowLeft = "\u2190";
        public const string ArrowRight = "\u2192";
        public const string ArrowUp = "\u2191";
        public const string ArrowDown = "\u2193";
        public const string TriangleUp = "\u25B2";
        public const string TriangleDown = "\u25BC";
        public const string TriangleLeft = "\u25C0";
        public const string TriangleRight = "\u25B6";
        public const string Heart = "\u2665";
        public const string Star = "\u2605";
        public const string StarOutline = "\u2606";
        public const string Check = "\u2713";
        public const string Cross = "\u2715";
        public const string Dot = "\u25CF";
        public const string Bullet = "\u2022";
        public const string Ellipsis = "\u2026";
        public const string Degree = "\u00B0";
        public const string PlusMinus = "\u00B1";
        public const string Infinity = "\u221E";
        public const string Times = "\u00D7";

        public const string IconFood = "\uE080";
        public const string IconWave = "\uE081";
        public const string IconClock = "\uE082";
        public const string IconShield = "\uE083";
        public const string IconPoison = "\uE084";
        public const string IconFire = "\uE085";
        public const string IconBolt = "\uE086";
        public const string IconFrost = "\uE087";
        public const string IconSkull = "\uE088";
        public const string IconSword = "\uE089";
        public const string IconCrown = "\uE08A";
        public const string IconAnt = "\uE08B";

        public const string KeyEsc = "\uE000";
        public const string KeyTab = "\uE001";
        public const string KeySpace = "\uE002";
        public const string KeyEnter = "\uE003";
        public const string KeyShift = "\uE004";
        public const string KeyCtrl = "\uE005";
        public const string KeyAlt = "\uE006";
        public const string KeyDel = "\uE007";
        public const string KeyUp = "\uE008";
        public const string KeyDown = "\uE009";
        public const string KeyLeft = "\uE00A";
        public const string KeyRight = "\uE00B";
        public const string Key0 = "\uE010";
        public const string Key1 = "\uE011";
        public const string Key2 = "\uE012";
        public const string Key3 = "\uE013";
        public const string Key4 = "\uE014";
        public const string Key5 = "\uE015";
        public const string Key6 = "\uE016";
        public const string Key7 = "\uE017";
        public const string Key8 = "\uE018";
        public const string Key9 = "\uE019";
        public const string KeyA = "\uE020";
        public const string KeyB = "\uE021";
        public const string KeyC = "\uE022";
        public const string KeyD = "\uE023";
        public const string KeyE = "\uE024";
        public const string KeyF = "\uE025";
        public const string KeyG = "\uE026";
        public const string KeyH = "\uE027";
        public const string KeyI = "\uE028";
        public const string KeyJ = "\uE029";
        public const string KeyK = "\uE02A";
        public const string KeyL = "\uE02B";
        public const string KeyM = "\uE02C";
        public const string KeyN = "\uE02D";
        public const string KeyO = "\uE02E";
        public const string KeyP = "\uE02F";
        public const string KeyQ = "\uE030";
        public const string KeyR = "\uE031";
        public const string KeyS = "\uE032";
        public const string KeyT = "\uE033";
        public const string KeyU = "\uE034";
        public const string KeyV = "\uE035";
        public const string KeyW = "\uE036";
        public const string KeyX = "\uE037";
        public const string KeyY = "\uE038";
        public const string KeyZ = "\uE039";
        public const string KeyF1 = "\uE040";
        public const string KeyF2 = "\uE041";
        public const string KeyF3 = "\uE042";
        public const string KeyF4 = "\uE043";
        public const string KeyF5 = "\uE044";
        public const string KeyF6 = "\uE045";
        public const string KeyF7 = "\uE046";
        public const string KeyF8 = "\uE047";
        public const string KeyF9 = "\uE048";
        public const string KeyF10 = "\uE049";
        public const string KeyF11 = "\uE04A";
        public const string KeyF12 = "\uE04B";
        public const string MouseLeft = "\uE050";
        public const string MouseRight = "\uE051";
        public const string MouseMiddle = "\uE052";
        public const string Mouse = "\uE053";
        public const string PadA = "\uE060";
        public const string PadB = "\uE061";
        public const string PadX = "\uE062";
        public const string PadY = "\uE063";
        public const string PadLb = "\uE064";
        public const string PadRb = "\uE065";
        public const string PadLt = "\uE066";
        public const string PadRt = "\uE067";
        public const string PadLeftStick = "\uE068";
        public const string PadRightStick = "\uE069";
        public const string PadDpadUp = "\uE06A";
        public const string PadDpadDown = "\uE06B";
        public const string PadDpadLeft = "\uE06C";
        public const string PadDpadRight = "\uE06D";
        public const string PadStart = "\uE06E";
        public const string PadSelect = "\uE06F";

        /// <summary>The prompt for a letter or digit key, or an empty string if it has none.</summary>
        public static string Key(char key)
        {
            char upper = char.ToUpperInvariant(key);
            if (upper >= 'A' && upper <= 'Z')
            {
                return ((char)(0xE020 + (upper - 'A'))).ToString();
            }

            if (upper >= '0' && upper <= '9')
            {
                return ((char)(0xE010 + (upper - '0'))).ToString();
            }

            return string.Empty;
        }
    }
}
